version: '3'

services:
  app:
    build:
      context: ../project
      dockerfile: ../docker/php/Dockerfile
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ../project/:/var/www
    networks:
      - app-network
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
    volumes:
      - ../project/:/var/www
      - ../docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network
  db:
    image: postgres:latest
    container_name: db
    restart: always
    tty: true
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpassword
      - POSTGRES_DB=testdb
    volumes:
      - /var/lib/postgresql/data
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  dbdate:
    driver: local